// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/alewkinr/example-google-wire/internal"
)

// Injectors from wire.go:

func InitializeEvent() (internal.Event, error) {
	message := internal.NewMessage()
	greeter := internal.NewGreeter(message)
	event, err := internal.NewEvent(greeter)
	if err != nil {
		return internal.Event{}, err
	}
	return event, nil
}
